#!/usr/bin/env python3
# HTML Report Assembly script for MicroSnake
# Author: Dawid X (dawidx1233)

import argparse
import os
import pandas as pd
import base64

def image_to_base64(path):
    with open(path, "rb") as image_file:
        return base64.b64encode(image_file.read()).decode('utf-8')

def build_report(args):
    # Load alpha diversity summary
    alpha_df = pd.read_csv(args.alpha, sep="\t")
    alpha_summary = alpha_df.describe().to_html(classes='table table-striped table-hover')
    
    # Load differential abundance summary (top 10 significant)
    deseq_df = pd.read_csv(args.deseq, sep="\t")
    significant = deseq_df[deseq_df['padj'] < 0.05].sort_values(by='padj')
    sig_summary = significant.head(10).to_html(classes='table table-striped table-hover')
    
    # Convert plots to base64 for embedding
    pcoa_b64 = image_to_base64(args.pcoa)
    barplot_b64 = image_to_base64(args.barplot)
    
    # Simple HTML template
    html_content = f"""
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>MicroSnake Microbiome Analysis Report</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
        <style>
            body {{ padding: 20px; background-color: #f8f9fa; }}
            .card {{ margin-bottom: 20px; box-shadow: 0 4px 6px rgba(0,0,0,0.1); }}
            .plot-img {{ max-width: 100%; height: auto; }}
        </style>
    </head>
    <body>
        <div class="container">
            <header class="pb-3 mb-4 border-bottom">
                <span class="fs-4">🧬 <b>MicroSnake</b> — Microbiome Analysis Pipeline Report</span>
            </header>

            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header bg-primary text-white">📋 Pipeline Execution Summary</div>
                        <div class="card-body">
                            <p>This report summarizes the microbiome analysis results generated by the <b>MicroSnake</b> pipeline.</p>
                            <ul>
                                <li><b>16S rRNA Amplicon Module:</b> Enabled (DADA2 ASV calling)</li>
                                <li><b>Shotgun Metagenomics Module:</b> Enabled (MetaPhlAn4 / HUMAnN3)</li>
                                <li><b>MultiQC Report:</b> <a href="qc/multiqc_report.html" target="_blank">View MultiQC Report</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-6">
                    <div class="card">
                        <div class="card-header bg-success text-white">📊 Alpha Diversity Summary</div>
                        <div class="card-body">
                            {alpha_summary}
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="card">
                        <div class="card-header bg-success text-white">📍 Beta Diversity (PCoA Ordination)</div>
                        <div class="card-body text-center">
                            <img class="plot-img" src="data:image/png;base64,{pcoa_b64}" alt="PCoA Plot">
                        </div>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-6">
                    <div class="card">
                        <div class="card-header bg-info text-white">🌿 Taxonomic Composition</div>
                        <div class="card-body text-center">
                            <img class="plot-img" src="data:image/png;base64,{barplot_b64}" alt="Taxa Barplot">
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="card">
                        <div class="card-header bg-danger text-white">🔬 Top 10 Differentially Abundant Taxa (DESeq2)</div>
                        <div class="card-body">
                            {sig_summary if len(significant) > 0 else "<p class='text-muted'>No significant differentially abundant taxa found.</p>"}
                        </div>
                    </div>
                </div>
            </div>

            <footer class="pt-3 mt-4 text-muted border-top">
                Generated automatically by MicroSnake. Author: dawidx1233.
            </footer>
        </div>
    </body>
    </html>
    """
    
    with open(args.output, "w") as f:
        f.write(html_content)
    print(f"HTML Report generated and written to {args.output}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Generate HTML report")
    parser.add_argument("--multiqc", type=str, required=True)
    parser.add_argument("--alpha", type=str, required=True)
    parser.add_argument("--pcoa", type=str, required=True)
    parser.add_argument("--barplot", type=str, required=True)
    parser.add_argument("--deseq", type=str, required=True)
    parser.add_argument("--output", type=str, required=True)
    
    args = parser.parse_args()
    build_report(args)
